source 'http://rubygems.org'

gem 'rails', git: 'git://github.com/rails/rails.git' #'3.1.0.rc4'

gem 'sass-rails', git: 'git://github.com/rails/sass-rails.git' #, "~> 3.1.0.rc"
gem 'coffee-script'
gem 'jquery-rails'
gem 'uglifier'
gem 'rake'
gem 'bson_ext'
gem 'mechanize'
gem 'mongoid'
gem 'oauth'
gem 'haml', git: 'git://github.com/nex3/haml.git'
gem 'haml-rails', git: 'git://github.com/indirect/haml-rails.git'
gem 'sass', git: 'git://github.com/nex3/sass.git'
gem 'omniauth', git: 'git://github.com/intridea/omniauth.git'
gem "jquery-rails"
gem 'json'
gem 'mongoid_rails_migrations', require: false
gem 'feedzirra'
gem 'settingslogic'
gem 'kaminari'

group :development, :test do
  gem 'heroku'
  gem 'yard'
  gem 'rr'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'mongoid-rspec'
  gem 'fabrication'
  gem 'wirble'
  gem 'spork'
  gem 'fuubar'
  gem 'tapp'
  gem 'wirble'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-spork', git: 'git://github.com/guard/guard-spork.git'
  gem 'rb-fsevent'
  gem 'growl'
end
