defaults: &defaults
  uri: <%= ENV['MONGOHQ_URL'] %>
  #host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  uri: <%= ENV['MONGOHQ_URL'] %>
  #<<: *defaults
  #database: rsss_development

test:
  uri: <%= ENV['MONGOHQ_URL'] %>
  #<<: *defaults
  #database: rsss_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
  #<<: *defaults
  #host: <%= ENV['MONGOID_HOST'] %>
  #port: <%= ENV['MONGOID_PORT'] %>
  #username: <%= ENV['MONGOID_USERNAME'] %>
  #password: <%= ENV['MONGOID_PASSWORD'] %>
  #database: <%= ENV['MONGOID_DATABASE'] %>
